# copyright: 2023 EUMETSAT
# license: LICENSE.txt
name: cmts_GHRSST24
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.8
  - conda-forge::jupyterlab
  - conda-forge::ipywidgets
  - conda-forge::xarray
  - conda-forge::dask
  - conda-forge::netcdf4
  - conda-forge::bokeh
  - conda-forge::ipykernel
  - conda-forge::pydap>3.3.0
  - conda-forge::matplotlib
  - conda-forge::beautifulsoup4
  - conda-forge::lxml