# copyright: 2023 EUMETSAT
# license: LICENSE.txt
name: cmts_GHRSST24
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.9
  - conda-forge::jupyterlab
  - conda-forge::numpy=1.25
  - conda-forge::xarray=2023.7.0
  - conda-forge::dask
  - conda-forge::netcdf4
  - conda-forge::bokeh
  - conda-forge::ipykernel
  - conda-forge::pydap>3.3.0
  - conda-forge::matplotlib
